### DISCUSSION TITLE
Ability to change scrollbar size

### DISCUSSION THREAD

**Discussion by AlexWayfer** [pulsar-edit/.github#235] [Core Application & Packages]
Hello.

I have a custom stylesheet with scrollbar size (for files tree) change:

```scss
.scrollbars-visible-always /deep/ ::-webkit-scrollbar {
	width: 18px;
}
```

Now I see it doesn't work.

And I can't find the new scrollbar element via Inspection in DevTools.

Also I see no setting for its size.

So, how I can increase its width? With custom style. Or can you please add a setting for its size?

It's really small for me right now:

![image](https://github.com/pulsar-edit/.github/assets/6510020/163986f4-3c90-40cf-bb32-3e356a2c2e50)

**Comment by AlexWayfer** [comment]
Oh, I've just found: remove `/deep/`. :sweat_smile:

```scss
.scrollbars-visible-always ::-webkit-scrollbar {
  width: 18px;
}
```

Sorry.
